### ISSUE TITLE
404 Not Found td-react-native-sdk

### ISSUE THREAD

**Issue by LinHaobo0221** [treasure-data/td-react-native-sdk#10]
After run: npm install td-react-native-sdk --save, below error come out.

Would you please do me a favor to check this in npm repos?

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/td-react-native-sdk - Not found
npm ERR! 404
npm ERR! 404  'td-react-native-sdk@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by tung-vu-td** [comment]
Thank you @LinHaobo0221 for pointing this out. This was a miss by us due to the beta nature of this repo.
The SDK is now available at https://www.npmjs.com/package/td-react-native-sdk
